# This is a comment line
FROM ubi8/ubi:8.3
LABEL description="This is a custom httpd container image"
MAINTAINER John Doe <jdoe@xyz.com>
RUN yum install -y httpd && \
    yum clean all
EXPOSE 80

#WORKDIR /
#ADD /home/student/Desktop/myfile.zip /opt/ziptest
RUN yum install -y unzip && yum clean all
ADD myzip.zip /opt/ziptest.zip
RUN unzip -d /opt/myzip /opt/ziptest.zip
RUN pwd
RUN ls -al /opt/
#RUN ls -al /tozip/
RUN cat /opt/myzip/tozip/myfile > /opt/out.txt
RUN cat /opt/out.txt

ENV LogLevel "info"
#ADD http://someserver.com/filename.pdf /var/www/html
#COPY ./src/ /var/www/html/
#USER apache
RUN mkdir /opt/mgk
VOLUME ["/opt/mgk"]
ENTRYPOINT ["/usr/sbin/httpd"]
CMD ["-D", "FOREGROUND"]
#ENTRYPOINT ["/bin/date", "+%H:%M"]

